"""add voltage thresholds to device_profiles and is_locked_out to devices

Revision ID: 42d3384f7b19
Revises: ac6b3131044c
Create Date: 2026-09-14 02:40:04.127569

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42d3384f7b19'
down_revision: str | None = 'ac6b3131044c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_profiles', sa.Column('min_voltage_v', sa.Float(), nullable=True))
    op.add_column('device_profiles', sa.Column('max_voltage_v', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('is_locked_out', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'is_locked_out')
    op.drop_column('device_profiles', 'max_voltage_v')
    op.drop_column('device_profiles', 'min_voltage_v')
    # ### end Alembic commands ###