/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register User */
        post: operations["register_user_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iot/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Telemetry */
        post: operations["receive_telemetry_api_v1_iot_telemetry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iot/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat */
        post: operations["heartbeat_api_v1_iot_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iot/commands/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Commands */
        get: operations["list_pending_commands_api_v1_iot_commands_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iot/commands/{command_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ack Command */
        post: operations["ack_command_api_v1_iot_commands__command_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Users */
        get: operations["admin_list_users_api_v1_admin_users_get"];
        put?: never;
        /** Admin Create User */
        post: operations["admin_create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get User */
        get: operations["admin_get_user_api_v1_admin_users__user_id__get"];
        put?: never;
        post?: never;
        /** Admin Delete User */
        delete: operations["admin_delete_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update User */
        patch: operations["admin_update_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Sites */
        get: operations["admin_list_sites_api_v1_admin_sites_get"];
        put?: never;
        /** Admin Create Site */
        post: operations["admin_create_site_api_v1_admin_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Site */
        get: operations["admin_get_site_api_v1_admin_sites__site_id__get"];
        put?: never;
        post?: never;
        /** Admin Delete Site */
        delete: operations["admin_delete_site_api_v1_admin_sites__site_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update Site */
        patch: operations["admin_update_site_api_v1_admin_sites__site_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/sites/{site_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Site Members */
        get: operations["admin_list_site_members_api_v1_admin_sites__site_id__members_get"];
        put?: never;
        /** Admin Add Site Member */
        post: operations["admin_add_site_member_api_v1_admin_sites__site_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sites/{site_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin Remove Site Member */
        delete: operations["admin_remove_site_member_api_v1_admin_sites__site_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sites/{site_id}/tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Tariffs */
        get: operations["admin_list_tariffs_api_v1_admin_sites__site_id__tariffs_get"];
        put?: never;
        /** Admin Create Tariff */
        post: operations["admin_create_tariff_api_v1_admin_sites__site_id__tariffs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Devices */
        get: operations["admin_list_devices_api_v1_admin_devices_get"];
        put?: never;
        /** Admin Create Device */
        post: operations["admin_create_device_api_v1_admin_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Device */
        get: operations["admin_get_device_api_v1_admin_devices__device_id__get"];
        put?: never;
        post?: never;
        /** Admin Delete Device */
        delete: operations["admin_delete_device_api_v1_admin_devices__device_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update Device */
        patch: operations["admin_update_device_api_v1_admin_devices__device_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/devices/{device_id}/reassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Reassign */
        post: operations["admin_reassign_api_v1_admin_devices__device_id__reassign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Profiles */
        get: operations["admin_list_profiles_api_v1_admin_profiles_get"];
        put?: never;
        /** Admin Create Profile */
        post: operations["admin_create_profile_api_v1_admin_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Get Profile */
        get: operations["admin_get_profile_api_v1_admin_profiles__profile_id__get"];
        put?: never;
        post?: never;
        /** Admin Delete Profile */
        delete: operations["admin_delete_profile_api_v1_admin_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        /** Admin Update Profile */
        patch: operations["admin_update_profile_api_v1_admin_profiles__profile_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Events */
        get: operations["admin_list_events_api_v1_admin_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin List Anomalies
         * @description Mínimo viable: la etapa 9 es la que puebla `AnomalyAlert` de verdad.
         */
        get: operations["admin_list_anomalies_api_v1_admin_anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Dashboard Metrics */
        get: operations["admin_dashboard_metrics_api_v1_admin_dashboard_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/by-site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Dashboard By Site */
        get: operations["admin_dashboard_by_site_api_v1_admin_dashboard_by_site_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/by-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Dashboard By Profile */
        get: operations["admin_dashboard_by_profile_api_v1_admin_dashboard_by_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Dashboard Overview */
        get: operations["admin_dashboard_overview_api_v1_admin_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Sites */
        get: operations["get_my_sites_api_v1_app_sites_get"];
        put?: never;
        /**
         * Create My Site
         * @description Alta de sitio por el usuario final — a diferencia de
         *     `POST /api/v1/admin/sites`, acá quien lo crea queda automáticamente
         *     como su primer miembro (rol "owner"), porque no hay un admin del otro
         *     lado que lo agregue después.
         */
        post: operations["create_my_site_api_v1_app_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/sites/{site_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site Devices */
        get: operations["get_site_devices_api_v1_app_sites__site_id__devices_get"];
        put?: never;
        /**
         * Create My Device
         * @description Alta de dispositivo por el usuario final dentro de un sitio propio.
         *
         *     Crea un `DeviceProfile` propio para el dispositivo (el usuario final no
         *     tiene por qué manejar perfiles como concepto aparte) y devuelve el
         *     `public_id`/`secret` que hay que cargar en el dispositivo físico vía el
         *     portal cautivo de aprovisionamiento (etapa 12) — el mismo flujo que ya
         *     usa el admin, solo que ahora también lo puede iniciar el usuario dueño
         *     del sitio.
         */
        post: operations["create_my_device_api_v1_app_sites__site_id__devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim A Device
         * @description El usuario ingresa el `public_id` que el dispositivo expone en su
         *     aprovisionamiento local (etapa 12) y el sitio destino, del que debe ser
         *     miembro. No requiere `get_current_site_member` como dependencia porque
         *     `site_id` viaja en el body, no en el path — se valida aquí mismo.
         */
        post: operations["claim_a_device_api_v1_app_devices_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Detail */
        get: operations["get_device_detail_api_v1_app_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/{device_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Telemetry */
        get: operations["get_device_telemetry_api_v1_app_devices__device_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/{device_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Events */
        get: operations["get_device_events_api_v1_app_devices__device_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/{device_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Metrics */
        get: operations["get_device_metrics_api_v1_app_devices__device_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/{device_id}/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Cost */
        get: operations["get_device_cost_api_v1_app_devices__device_id__cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/{device_id}/consumption": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Consumption
         * @description Vista para graficar consumo real por rango de tiempo seleccionable
         *     — misma fuente de verdad que `/cost` (`compute_daily_consumption`),
         *     solo agregada distinto. `granularity=month` tiene sentido con `days`
         *     grande (ej. 365); con `days` chico simplemente da uno o dos puntos.
         *
         *     `start`/`end` (formato "YYYY-MM-DD") arman un rango personalizado en
         *     vez de `days` — para el selector de fecha, `earliest_date` en la
         *     respuesta es el límite inferior real (la primera lectura que existe).
         *
         *     `granularity="hour"` es la vista "hoy, trazado a lo largo del día" —
         *     ignora `days`/`start`/`end` y siempre usa el día calendario UTC actual
         *     (ver `compute_hourly_consumption`).
         */
        get: operations["get_device_consumption_api_v1_app_devices__device_id__consumption_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/{device_id}/prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Prediction */
        get: operations["get_device_prediction_api_v1_app_devices__device_id__prediction_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/{device_id}/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch */
        post: operations["switch_api_v1_app_devices__device_id__switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/devices/{device_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate */
        post: operations["reactivate_api_v1_app_devices__device_id__reactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Notifications */
        get: operations["get_my_notifications_api_v1_app_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Notification Preference */
        patch: operations["set_notification_preference_api_v1_app_notifications_preferences_patch"];
        trace?: never;
    };
    "/api/v1/app/voice/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice Query */
        post: operations["voice_query_api_v1_app_voice_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Vida del proceso, sin tocar la base de datos — no debe fallar solo
         *     porque Postgres esté caído (eso es lo que verifica /health/ready).
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness Check */
        get: operations["readiness_check_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminEventOut */
        AdminEventOut: {
            /** Id */
            id: number;
            /** Device Id */
            device_id: number;
            /** Type */
            type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdminOverviewOut */
        AdminOverviewOut: {
            global_metrics: components["schemas"]["GlobalMetricsOut"];
            /** By Site */
            by_site: components["schemas"]["SiteMetricsOut"][];
            /** By Profile */
            by_profile: components["schemas"]["ProfileMetricsOut"][];
        };
        /** Body_login_for_access_token_api_v1_auth_login_post */
        Body_login_for_access_token_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** ClaimIn */
        ClaimIn: {
            /** Public Id */
            public_id: string;
            /** Site Id */
            site_id: number;
        };
        /** CommandAckIn */
        CommandAckIn: {
            /**
             * Actual State
             * @enum {string}
             */
            actual_state: "ON" | "OFF";
        };
        /** CommandOut */
        CommandOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** ConsumptionPointOut */
        ConsumptionPointOut: {
            /**
             * Period
             * @description "YYYY-MM-DD" si granularity="day", "YYYY-MM" si "month", "YYYY-MM-DDTHH" si "hour".
             */
            period: string;
            /** Kwh */
            kwh: number;
        };
        /** DeviceConsumptionOut */
        DeviceConsumptionOut: {
            /** Device Id */
            device_id: number;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "hour" | "day" | "month";
            /** Points */
            points: components["schemas"]["ConsumptionPointOut"][];
            /**
             * Earliest Date
             * @description "YYYY-MM-DD" de la lectura más antigua del dispositivo — límite inferior real para un rango personalizado, null si nunca reportó telemetría.
             */
            earliest_date?: string | null;
        };
        /**
         * DeviceCostOut
         * @description Costo real del período analizado (no una proyección) — cada día se
         *     valora con la tarifa que estaba vigente ese día. Ver `DevicePredictionOut`
         *     para la proyección a futuro.
         */
        DeviceCostOut: {
            /** Device Id */
            device_id: number;
            /** Days Analyzed */
            days_analyzed: number;
            /** Total Kwh */
            total_kwh: number;
            /** Total Cost */
            total_cost: number;
            /** Currency */
            currency: string;
            /**
             * Used Default Tariff
             * @description True si el sitio no tiene ninguna Tariff configurada para algún día del período.
             */
            used_default_tariff: boolean;
        };
        /** DeviceCreateIn */
        DeviceCreateIn: {
            /** Public Id */
            public_id: string;
            /** Name */
            name: string;
            /** Site Id */
            site_id?: number | null;
            /** Profile Id */
            profile_id?: number | null;
        };
        /** DeviceCreateOut */
        DeviceCreateOut: {
            /** Id */
            id: number;
            /** Public Id */
            public_id: string;
            /** Name */
            name: string;
            /** Site Id */
            site_id: number | null;
            /** Profile Id */
            profile_id: number | null;
            /**
             * Secret
             * @description Solo se muestra una vez; no se puede recuperar después.
             */
            secret: string;
        };
        /**
         * DeviceMetricsOut
         * @description Vista mínima viable — la etapa 8 la reemplaza por agregaciones
         *     día/mes reales.
         */
        DeviceMetricsOut: {
            /** Device Id */
            device_id: number;
            /** Readings Count */
            readings_count: number;
            /** Latest Voltage */
            latest_voltage?: number | null;
            /** Latest Current */
            latest_current?: number | null;
            /** Latest Power */
            latest_power?: number | null;
            /** Last Seen At */
            last_seen_at?: string | null;
        };
        /** DeviceOut */
        DeviceOut: {
            /** Id */
            id: number;
            /** Public Id */
            public_id: string;
            /** Name */
            name: string;
            /** Site Id */
            site_id: number | null;
            /** Desired State */
            desired_state: string;
            /** Actual State */
            actual_state: string;
            /** Is Locked Out */
            is_locked_out: boolean;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Firmware Version */
            firmware_version: string | null;
        };
        /**
         * DevicePredictionOut
         * @description Refleja directamente una fila persistida de `Prediction` — generada
         *     de forma perezosa y cacheada (ver `app/services/predictions.py`).
         */
        DevicePredictionOut: {
            /** Device Id */
            device_id: number;
            /** Horizon */
            horizon: string;
            /** Projected Kwh */
            projected_kwh: number;
            /** Projected Cost */
            projected_cost: number;
            /** Method */
            method: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** DeviceReassignIn */
        DeviceReassignIn: {
            /** Site Id */
            site_id: number | null;
        };
        /**
         * DeviceSelfCreateIn
         * @description Alta de dispositivo por un usuario final dentro de un sitio propio.
         *
         *     A diferencia de `admin_api.DeviceCreateIn`, acá no se pide `profile_id`
         *     — el usuario final no debería tener que entender qué es un
         *     `DeviceProfile` primero; el endpoint crea uno propio para el
         *     dispositivo con el umbral que el usuario indique (o el default).
         */
        DeviceSelfCreateIn: {
            /** Public Id */
            public_id: string;
            /** Name */
            name: string;
            /**
             * Max Current A
             * @default 15
             */
            max_current_a: number;
        };
        /** DeviceUpdateIn */
        DeviceUpdateIn: {
            /** Name */
            name?: string | null;
            /** Profile Id */
            profile_id?: number | null;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GlobalMetricsOut */
        GlobalMetricsOut: {
            /** Total Sites */
            total_sites: number;
            /** Total Users */
            total_users: number;
            /** Total Devices */
            total_devices: number;
            /** Devices Online */
            devices_online: number;
            /** Devices Offline */
            devices_offline: number;
            /** Critical Events Last 24H */
            critical_events_last_24h: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatAck */
        HeartbeatAck: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: number;
            /** Channel */
            channel: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Read At */
            read_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NotificationPreferenceIn */
        NotificationPreferenceIn: {
            /** Channel */
            channel: string;
            /** Enabled */
            enabled: boolean;
        };
        /** NotificationPreferenceOut */
        NotificationPreferenceOut: {
            /** Channel */
            channel: string;
            /** Enabled */
            enabled: boolean;
        };
        /** ProfileCreateIn */
        ProfileCreateIn: {
            /** Name */
            name: string;
            /** Site Id */
            site_id?: number | null;
            /**
             * Max Current A
             * @default 15
             */
            max_current_a: number;
            /** Min Voltage V */
            min_voltage_v?: number | null;
            /** Max Voltage V */
            max_voltage_v?: number | null;
            /**
             * Auto Cutoff Enabled
             * @default true
             */
            auto_cutoff_enabled: boolean;
        };
        /** ProfileMetricsOut */
        ProfileMetricsOut: {
            /** Profile Id */
            profile_id: number;
            /** Profile Name */
            profile_name: string;
            /** Device Count */
            device_count: number;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Site Id */
            site_id: number | null;
            /** Max Current A */
            max_current_a: number;
            /** Min Voltage V */
            min_voltage_v: number | null;
            /** Max Voltage V */
            max_voltage_v: number | null;
            /** Auto Cutoff Enabled */
            auto_cutoff_enabled: boolean;
        };
        /** ProfileUpdateIn */
        ProfileUpdateIn: {
            /** Max Current A */
            max_current_a?: number | null;
            /** Min Voltage V */
            min_voltage_v?: number | null;
            /** Max Voltage V */
            max_voltage_v?: number | null;
            /** Auto Cutoff Enabled */
            auto_cutoff_enabled?: boolean | null;
        };
        /** SiteMemberIn */
        SiteMemberIn: {
            /** User Id */
            user_id: number;
            /**
             * Role
             * @default member
             */
            role: string;
        };
        /** SiteMemberOut */
        SiteMemberOut: {
            /** Id */
            id: number;
            /** Site Id */
            site_id: number;
            /** User Id */
            user_id: number;
            /** Role */
            role: string;
        };
        /** SiteMetricsOut */
        SiteMetricsOut: {
            /** Site Id */
            site_id: number;
            /** Site Name */
            site_name: string;
            /** Device Count */
            device_count: number;
            /** Devices Online */
            devices_online: number;
        };
        /** SiteOut */
        SiteOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
        };
        /** SiteUpdateIn */
        SiteUpdateIn: {
            /** Name */
            name?: string | null;
            /** Kind */
            kind?: string | null;
        };
        /** SwitchIn */
        SwitchIn: {
            /**
             * Desired State
             * @enum {string}
             */
            desired_state: "ON" | "OFF";
        };
        /** TariffCreateIn */
        TariffCreateIn: {
            /** Price Per Kwh */
            price_per_kwh: number;
            /**
             * Currency
             * @default MXN
             */
            currency: string;
        };
        /** TariffOut */
        TariffOut: {
            /** Id */
            id: number;
            /** Site Id */
            site_id: number;
            /** Currency */
            currency: string;
            /** Price Per Kwh */
            price_per_kwh: number;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
        };
        /** TelemetryAck */
        TelemetryAck: {
            /**
             * Status
             * @default success
             * @enum {string}
             */
            status: "success" | "duplicate";
            /**
             * Is Out Of Order
             * @default false
             */
            is_out_of_order: boolean;
            command?: components["schemas"]["CommandOut"] | null;
        };
        /**
         * TelemetryIn
         * @description Contrato de telemetría versionado (ver roadmap/ORIGINAL-SPEC-README.md).
         *
         *     Los nombres de campo usan unidades explícitas (`_v`, `_a`, `_w`, `_kwh`,
         *     `_hz`) para que no haya ambigüedad de unidades entre firmware y backend.
         */
        TelemetryIn: {
            /** Sequence */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Voltage V */
            voltage_v: number;
            /** Current A */
            current_a: number;
            /** Power W */
            power_w: number;
            /** Energy Kwh */
            energy_kwh: number;
            /**
             * Frequency Hz
             * @default 60
             */
            frequency_hz: number;
            /**
             * Power Factor
             * @default 1
             */
            power_factor: number;
            /**
             * Relay State
             * @enum {string}
             */
            relay_state: "ON" | "OFF";
        };
        /** TelemetryOut */
        TelemetryOut: {
            /** Id */
            id: number;
            /** Sequence */
            sequence: number;
            /** Voltage */
            voltage: number;
            /** Current */
            current: number;
            /** Power */
            power: number;
            /** Frequency */
            frequency: number;
            /** Power Factor */
            power_factor: number;
            /** Energy */
            energy: number;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default user
             */
            role: string;
        };
        /** UserCreateIn */
        UserCreateIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default user
             */
            role: string;
        };
        /** UserUpdateIn */
        UserUpdateIn: {
            /** Role */
            role?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VoiceQueryIn
         * @description Texto ya transcrito por STT en el celular — este endpoint nunca
         *     recibe audio, solo texto (etapa 14).
         */
        VoiceQueryIn: {
            /** Text */
            text: string;
        };
        /**
         * VoiceQueryOut
         * @description `spoken_text` es lo único que el celular necesita pasarle a su TTS
         *     nativo — siempre construido a partir del resultado real de la acción o
         *     consulta, nunca un texto genérico (ver IA-Assistant/ia_assistant/responder.py).
         */
        VoiceQueryOut: {
            /** Spoken Text */
            spoken_text: string;
            /** Action Taken */
            action_taken: boolean;
            /** Intent Type */
            intent_type: string;
            /** Device Id */
            device_id?: number | null;
        };
        /** SiteCreateIn */
        app__schemas__admin_api__SiteCreateIn: {
            /** Name */
            name: string;
            /**
             * Kind
             * @default otro
             */
            kind: string;
        };
        /** UserOut */
        app__schemas__admin_api__UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
        };
        /** DeviceStateOut */
        app__schemas__app_api__DeviceStateOut: {
            /** Device Id */
            device_id: number;
            /** Desired State */
            desired_state: string;
            /** Actual State */
            actual_state: string;
            /** Is Locked Out */
            is_locked_out: boolean;
        };
        /**
         * SiteCreateIn
         * @description Alta de sitio por el propio usuario final (a diferencia de
         *     `admin_api.SiteCreateIn`, acá quien crea el sitio queda automáticamente
         *     como su primer miembro con rol "owner" — ver `create_my_site`).
         */
        app__schemas__app_api__SiteCreateIn: {
            /** Name */
            name: string;
            /**
             * Kind
             * @default otro
             */
            kind: string;
        };
        /** UserOut */
        app__schemas__auth__UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
        };
        /** DeviceStateOut */
        app__schemas__iot__DeviceStateOut: {
            /** Device Id */
            device_id: number;
            /** Desired State */
            desired_state: string;
            /** Actual State */
            actual_state: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_user_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__auth__UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_for_access_token_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_telemetry_api_v1_iot_telemetry_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Esquema: "Device <public_id>:<secret>" */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_api_v1_iot_heartbeat_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Esquema: "Device <public_id>:<secret>" */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_commands_api_v1_iot_commands_pending_get: {
        parameters: {
            query?: never;
            header: {
                /** @description Esquema: "Device <public_id>:<secret>" */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_command_api_v1_iot_commands__command_id__ack_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Esquema: "Device <public_id>:<secret>" */
                authorization: string;
            };
            path: {
                command_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandAckIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__iot__DeviceStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__admin_api__UserOut"][];
                };
            };
        };
    };
    admin_create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__admin_api__UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_user_api_v1_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__admin_api__UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__admin_api__UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_sites_api_v1_admin_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"][];
                };
            };
        };
    };
    admin_create_site_api_v1_admin_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__schemas__admin_api__SiteCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_site_api_v1_admin_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_site_api_v1_admin_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_site_api_v1_admin_sites__site_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_site_members_api_v1_admin_sites__site_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_add_site_member_api_v1_admin_sites__site_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteMemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteMemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_remove_site_member_api_v1_admin_sites__site_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_tariffs_api_v1_admin_sites__site_id__tariffs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_tariff_api_v1_admin_sites__site_id__tariffs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TariffCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_devices_api_v1_admin_devices_get: {
        parameters: {
            query?: {
                site_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_device_api_v1_admin_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCreateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_device_api_v1_admin_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_device_api_v1_admin_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_device_api_v1_admin_devices__device_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_reassign_api_v1_admin_devices__device_id__reassign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceReassignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_profiles_api_v1_admin_profiles_get: {
        parameters: {
            query?: {
                site_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_profile_api_v1_admin_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_profile_api_v1_admin_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_profile_api_v1_admin_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_profile_api_v1_admin_profiles__profile_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_events_api_v1_admin_events_get: {
        parameters: {
            query?: {
                device_id?: number | null;
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_anomalies_api_v1_admin_anomalies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    admin_dashboard_metrics_api_v1_admin_dashboard_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalMetricsOut"];
                };
            };
        };
    };
    admin_dashboard_by_site_api_v1_admin_dashboard_by_site_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteMetricsOut"][];
                };
            };
        };
    };
    admin_dashboard_by_profile_api_v1_admin_dashboard_by_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileMetricsOut"][];
                };
            };
        };
    };
    admin_dashboard_overview_api_v1_admin_dashboard_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverviewOut"];
                };
            };
        };
    };
    get_my_sites_api_v1_app_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"][];
                };
            };
        };
    };
    create_my_site_api_v1_app_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__schemas__app_api__SiteCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_devices_api_v1_app_sites__site_id__devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_my_device_api_v1_app_sites__site_id__devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceSelfCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCreateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_a_device_api_v1_app_devices_claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_detail_api_v1_app_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_telemetry_api_v1_app_devices__device_id__telemetry_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_events_api_v1_app_devices__device_id__events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_metrics_api_v1_app_devices__device_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceMetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_cost_api_v1_app_devices__device_id__cost_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCostOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_consumption_api_v1_app_devices__device_id__consumption_get: {
        parameters: {
            query?: {
                days?: number;
                granularity?: string;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceConsumptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_prediction_api_v1_app_devices__device_id__prediction_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicePredictionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_api_v1_app_devices__device_id__switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__app_api__DeviceStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_api_v1_app_devices__device_id__reactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__app_api__DeviceStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_notifications_api_v1_app_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
        };
    };
    set_notification_preference_api_v1_app_notifications_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_query_api_v1_app_voice_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceQueryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceQueryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_check_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
