"""add_pzem_metrics

Revision ID: f7f813c4415b
Revises: '2474dee7c77e'
Create Date: 2026-09-09 11:11:35.137582

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f7f813c4415b'
down_revision: str | None = '2474dee7c77e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('frequency', sa.Float(), nullable=False))
    op.add_column('readings', sa.Column('power_factor', sa.Float(), nullable=False))
    op.add_column('readings', sa.Column('energy', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readings', 'energy')
    op.drop_column('readings', 'power_factor')
    op.drop_column('readings', 'frequency')
    # ### end Alembic commands ###